this should have thrown exception